### ISSUE TITLE
thisroot.sh

### ISSUE THREAD

**Issue by PsycheShaman** [tdietel/DaSciX#1]
Hi, just 2 quick questions:

(1).is the following file created by installing root?

/path/to/root/bin/_thisroot.sh_

i.e. all that has to be edited is the /path/to/root

(2). if you have edited your ".bashrc" file, is it still necessary to create the "env.sh" file?

**Comment by tdietel** [comment]
Yes, the file "thisroot.sh" gets created by the root installer, using the correct path will setup ROOT correctly.
If you add the commands to your ".bashrc", you no longer need the "env.sh" file.
